In [1]:
a = 1

In [2]:
a

In [1]:
print(a)

NameError: name 'a' is not defined

In [3]:
import numpy as np


In [4]:
x = np.array([1,2,3])

In [5]:
y = np.array([3,2,1])

In [6]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [7]:
z = [99,99,99]

In [8]:
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [10]:
grid = np.array([[1,2,3],
                 [4,5,6]])

In [11]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [12]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [14]:
np.concatenate([grid,grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
x = np.array([[9,8,7],
             [6,5,4]])

In [17]:
grid = np.array([1,2,3])

In [21]:
stacked = np.vstack([x, grid])

In [22]:
stacked

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [23]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

In [24]:
x1, x2, x3 = np.split(x, [3, 5])

In [25]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [26]:
grid = np.arange(16).reshape((4, 4))

In [27]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
upper, lower = np.vsplit(grid, [2])

In [29]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [30]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
left, right = np.split(grid, [2])

In [32]:
left

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])