In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [4]:
values = np.random.randint(1, 10, size=5)

In [6]:
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [8]:
big_array = np.random.randint(1, 100, size=1000000)
%time compute_reciprocals(big_array)

CPU times: user 2.33 s, sys: 0 ns, total: 2.33 s
Wall time: 2.33 s


array([0.01204819, 0.03448276, 0.01219512, ..., 0.04      , 0.02272727,
       0.02777778])

In [9]:
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]


In [10]:
%timeit (1.0 / big_array)

1.56 ms ± 13 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
np.array(5) / np.arange(1, 6)

array([5.        , 2.5       , 1.66666667, 1.25      , 1.        ])

In [12]:
x = np.arange(9).reshape((3, 3))

In [13]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])